### ISSUE TITLE
刷新页面一直在等待中

### ISSUE THREAD

**Issue by BWrong** [eliduty/vite-plugin-iconfont#1]
问题：刷新页面导致重新拉取iconfont，致使页面一直在等待中。
期望：调整拉取时机，应该只用在启动服务的时候拉取一次即可，后续可以监听iconfont url地址变化与否再做更新。
哥们，快点修复😀

**Comment by eliduty** [comment]
非常好的建议，已追踪到问题并解决，新版本已发布，请更新插件。

**Comment by eliduty** [comment]
> 问题：刷新页面导致重新拉取iconfont，致使页面一直在等待中。 期望：调整拉取时机，应该只用在启动服务的时候拉取一次即可，后续可以监听iconfont url地址变化与否再做更新。 哥们，快点修复😀
非常好的建议，已采纳并修复，请更新插件。

**Comment by eliduty** [comment]
非常好的建议，已修复，请更新插件。
