### ISSUE TITLE
希望生成路径 config.base 去掉

### ISSUE THREAD

**Issue by zcn78x** [eliduty/vite-plugin-iconfont#4]
config.base 是 链接的虚拟路径，由部署时决定，vite build 文件的存储路径并不会生成 config.base ,只有index.html 包含config.base 路径        
这样 npm preview 就完美了 ，否则找不到dist 的文件
index.mjs 中generateBundle
从
        const distPath = normalizePath(join(outDir, config.base, assetsDir, distUrl));
        改为
        const distPath = normalizePath(join(outDir,  assetsDir, distUrl));

**Comment by eliduty** [comment]
config.base 是会影响生产环境的构建结果，按理说应作为路径拼接的一部分，麻烦提供一下你的vite配置和项目目录结构截图，我参考一下，谢谢。

**Comment by eliduty** [comment]
> config.base 是 链接的虚拟路径，由部署时决定，vite build 文件的存储路径并不会生成 config.base ,只有index.html 包含config.base 路径 这样 npm preview 就完美了 ，否则找不到dist 的文件 index.mjs 中generateBundle 从 const distPath = normalizePath(join(outDir, config.base, assetsDir, distUrl)); 改为 const distPath = normalizePath(join(outDir, assetsDir, distUrl));

config.base 是会影响生产环境的构建结果，按理说应作为路径拼接的一部分，麻烦提供一下你的vite配置和项目目录结构截图，我参考一下，谢谢。
